
server:
  mode: production  # development/production
  port: 8080
  host: 0.0.0.0

# 认证配置
auth:
  strategies:
    - type: api_key
      enabled: true
      config: {}
    - type: anonymous
      enabled: false
      config:
        requests_per_minute: 10

# LLM后端配置
backends:
  load_balancer:
    strategy: round_robin
  providers:
    - name: default
      type: vllm
      url: http://192.168.8.6:8000/v1
      model: qwenOmni7
      api_key: "sk-VkxlIMJf6KLHpI8MN"
      # LLM模型参数配置（可选）
      parameters:
        temperature: 0.7          # 控制输出的随机性，范围 0.0-2.0
        max_tokens: 1000          # 最大输出token数
        top_p: 0.9               # 核采样参数，范围 0.0-1.0
        # top_k: 50              # Top-K采样参数（某些模型支持）
        # repetition_penalty: 1.1 # 重复惩罚，范围 0.0-2.0
        # frequency_penalty: 0.0  # 频率惩罚，范围 -2.0-2.0
        # presence_penalty: 0.0   # 存在惩罚，范围 -2.0-2.0
        # stop: ["<|endoftext|>"] # 停止词列表
        # seed: 42               # 随机种子，用于可重现的输出
        stream: false            # 是否使用流式输出

# 提示词配置
prompt:
  # 语言管理策略: 'merge' 或 'override'
  # 'merge' (默认): 将此处的语言列表与 languages.default.yaml 中的列表合并
  # 'override': 完全忽略默认语言列表，仅使用此文件中定义的语言
  # 如果要禁用某些默认语言，或只使用一个很小的自定义列表，请使用 'override'
  language_management_strategy: merge
  defaults:
    task: translate
    target_languages: ["en", "ja", "zh"]
  languages:
    - code: zh
      names:
        display: "中文"
        english: "Chinese"
        native: "中文"
      aliases: ["chinese", "中文", "汉语", "zh-cn"]
    - code: zh-hant
      names:
        display: "繁體中文"
        english: "Traditional Chinese"
        native: "繁體中文"
      aliases: ["zh-tw", "zh-hk", "traditional chinese", "繁体中文", "繁體中文"]
    - code: en
      names:
        display: "英文"
        english: "English"
        native: "English"
      aliases: ["english", "英文", "英语"]
    - code: ja
      names:
        display: "日文"
        english: "Japanese"
        native: "日本語"
      aliases: ["japanese", "日文", "日语", "日本語"]
    - code: ko
      names:
        display: "韩文"
        english: "Korean"
        native: "한국어"
      aliases: ["korean", "韩文", "韩语", "한국어"]
    - code: es
      names:
        display: "西班牙语"
        english: "Spanish"
        native: "Español"
      aliases: ["spanish", "西班牙语", "español"]
    - code: fr
      names:
        display: "法语"
        english: "French"
        native: "Français"
      aliases: ["french", "法语", "français"]
    - code: de
      names:
        display: "德语"
        english: "German"
        native: "Deutsch"
      aliases: ["german", "德语", "deutsch"]
    - code: ru
      names:
        display: "俄语"
        english: "Russian"
        native: "Русский"
      aliases: ["russian", "俄语", "俄文", "俄罗斯语"]
    - code: it
      names:
        display: "意大利语"
        english: "Italian"
        native: "Italiano"
      aliases: ["italian", "意大利语", "意大利文"]
  parsing:
    separators: [":", "：", "-", "—"]
    strict_mode: false
    validation:
      required_sections: []
      min_content_length: 1
      max_content_length: 3000

# 日志配置
logging:
  level: debug
  format: json 