# Lingualink Core 配置文件

# 服务器配置
server:
  mode: development  # development/production
  port: 8080
  host: 0.0.0.0

# 认证配置
auth:
  strategies:
    - type: api_key
      enabled: true
      config:
        keys:
          # 开发环境测试key
          dev-key-123:
            id: dev-user
            requests_per_minute: 100
          # 商业后端专用key - 无频率限制
          enterprise-key-2024:
            id: enterprise-backend
            requests_per_minute: -1  # -1表示无限制
    - type: anonymous
      enabled: true
      config:
        requests_per_minute: 10

# LLM后端配置
backends:
  load_balancer:
    strategy: round_robin
  providers:
    - name: default
      type: vllm
      url: http://192.168.8.6:8000/v1
      model: qwenOmni7
      api_key: "sk-VkxlIMJf6KLHpI8MN"

# 提示词配置
prompt:
  defaults:
    task: translate
    target_languages: ["en", "ja", "zh"]
  languages:
    - code: zh
      names:
        display: "中文"
        english: "Chinese"
        native: "中文"
      aliases: ["chinese", "中文", "汉语", "zh-cn"]
    - code: zh-hant
      names:
        display: "繁體中文"
        english: "Traditional Chinese"
        native: "繁體中文"
      aliases: ["zh-tw", "zh-hk", "traditional chinese", "繁体中文", "繁體中文"]
    - code: en
      names:
        display: "英文"
        english: "English"
        native: "English"
      aliases: ["english", "英文", "英语"]
    - code: ja
      names:
        display: "日文"
        english: "Japanese"
        native: "日本語"
      aliases: ["japanese", "日文", "日语", "日本語"]
    - code: ko
      names:
        display: "韩文"
        english: "Korean"
        native: "한국어"
      aliases: ["korean", "韩文", "韩语", "한국어"]
    - code: es
      names:
        display: "西班牙语"
        english: "Spanish"
        native: "Español"
      aliases: ["spanish", "西班牙语", "español"]
    - code: fr
      names:
        display: "法语"
        english: "French"
        native: "Français"
      aliases: ["french", "法语", "français"]
    - code: de
      names:
        display: "德语"
        english: "German"
        native: "Deutsch"
      aliases: ["german", "德语", "deutsch"]
  parsing:
    separators: [":", "：", "-", "—"]
    strict_mode: false
    validation:
      required_sections: []
      min_content_length: 1
      max_content_length: 10000

# 日志配置
logging:
  level: info
  format: json 