# config/languages.default.yaml
# 这是默认的语言定义。用户可以在自己的 config.yaml 中覆盖或添加。
prompt:
  languages:
    - code: zh
      names:
        display: "中文"
        english: "Chinese"
        native: "中文"
      aliases: ["chinese", "中文", "汉语", "zh-cn"]
    - code: zh-hant
      names:
        display: "繁體中文"
        english: "Traditional Chinese"
        native: "繁體中文"
      aliases: ["zh-tw", "zh-hk", "traditional chinese", "繁体中文", "繁體中文"]
    - code: en
      names:
        display: "英文"
        english: "English"
        native: "English"
      aliases: ["english", "英文", "英语"]
    - code: ja
      names:
        display: "日文"
        english: "Japanese"
        native: "日本語"
      aliases: ["japanese", "日文", "日语", "日本語"]
    - code: ko
      names:
        display: "韩文"
        english: "Korean"
        native: "한국어"
      aliases: ["korean", "韩文", "韩语", "한국어"]
    - code: fr
      names:
        display: "法文"
        english: "French"
        native: "Français"
      aliases: ["french", "法文", "法语", "français"]
    - code: de
      names:
        display: "德文"
        english: "German"
        native: "Deutsch"
      aliases: ["german", "德文", "德语", "deutsch"]
    - code: es
      names:
        display: "西班牙文"
        english: "Spanish"
        native: "Español"
      aliases: ["spanish", "西班牙文", "西班牙语", "español"]
    - code: it
      names:
        display: "意大利文"
        english: "Italian"
        native: "Italiano"
      aliases: ["italian", "意大利文", "意大利语", "italiano"]
    - code: pt
      names:
        display: "葡萄牙文"
        english: "Portuguese"
        native: "Português"
      aliases: ["portuguese", "葡萄牙文", "葡萄牙语", "português"]
    - code: ru
      names:
        display: "俄文"
        english: "Russian"
        native: "Русский"
      aliases: ["russian", "俄文", "俄语", "русский"]
    - code: ar
      names:
        display: "阿拉伯文"
        english: "Arabic"
        native: "العربية"
      aliases: ["arabic", "阿拉伯文", "阿拉伯语", "العربية"]
    - code: hi
      names:
        display: "印地文"
        english: "Hindi"
        native: "हिन्दी"
      aliases: ["hindi", "印地文", "印地语", "हिन्दी"]
    - code: th
      names:
        display: "泰文"
        english: "Thai"
        native: "ไทย"
      aliases: ["thai", "泰文", "泰语", "ไทย"]
    - code: vi
      names:
        display: "越南文"
        english: "Vietnamese"
        native: "Tiếng Việt"
      aliases: ["vietnamese", "越南文", "越南语", "tiếng việt"]
    - code: id
      names:
        display: "印尼文"
        english: "Indonesian"
        native: "Bahasa Indonesia"
      aliases: ["indonesian", "印尼文", "印尼语", "bahasa indonesia"]
    - code: ms
      names:
        display: "马来文"
        english: "Malay"
        native: "Bahasa Melayu"
      aliases: ["malay", "马来文", "马来语", "bahasa melayu"]